CREATE TABLE Groups (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
CREATE TABLE Notes (id INTEGER PRIMARY KEY AUTOINCREMENT, groupId INTEGER NOT NULL, username TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, FOREIGN KEY (groupId) REFERENCES Groups(id));
